// Generated by https://jsonschema.net/
export const schema = {
  $schema: "http://json-schema.org/draft-07/schema",
  $id: "http://example.com/example.json",
  type: "object",
  title: "The root schema",
  description: "The root schema comprises the entire JSON document.",
  default: {},
  examples: [
    {
      jasperReport: {
        source: "report",
        sourceDef: "",
        isTable: false,
        def: 0,
        containsFrame: "false",
        hasChild: true,
        attr: {
          name: "report._attributes.name",
        },
        child: [
          {
            parameter: {
              source: "report.data.userParameter",
              isTable: "true",
              hasChild: true,
              def: "0",
              containsFrame: "false",
              attr: {
                name: "_attributes.name",
                class: "_attributes.datatype",
              },
            },
          },
          {
            defaultValueExpression: {
              source: "report.data.userParameter",
              isTable: true,
              hasChild: false,
              def: 0,
              containsFrame: "false",
              attr: {
                value: "_attributes.initialValue",
              },
            },
          },
          {
            queryString: {
              source: "",
              sourceDef: "report.data.dataSource.select._cdata",
              isTable: false,
              def: '<![CDATA["#source#"]]>',
              containsFrame: "false",
              hasChild: false,
              attr: "",
            },
          },
          {
            field: {
              source: "report.data.dataSource.group.dataItem",
              sourceDef: "",
              isTable: true,
              def: 0,
              containsFrame: "false",
              hasChild: false,
              attr: {
                name: "_attributes.name",
                class: "_attributes.datatype",
              },
            },
          },
        ],
      },
    },
  ],
  required: ["jasperReport"],
  properties: {
    jasperReport: {
      $id: "#/properties/jasperReport",
      type: "object",
      title: "The jasperReport schema",
      description: "An explanation about the purpose of this instance.",
      default: {},
      examples: [
        {
          source: "report",
          sourceDef: "",
          isTable: false,
          def: 0,
          containsFrame: "false",
          hasChild: true,
          attr: {
            name: "report._attributes.name",
          },
          child: [
            {
              parameter: {
                source: "report.data.userParameter",
                isTable: "true",
                hasChild: true,
                def: "0",
                containsFrame: "false",
                attr: {
                  name: "_attributes.name",
                  class: "_attributes.datatype",
                },
              },
            },
            {
              defaultValueExpression: {
                source: "report.data.userParameter",
                isTable: true,
                hasChild: false,
                def: 0,
                containsFrame: "false",
                attr: {
                  value: "_attributes.initialValue",
                },
              },
            },
            {
              queryString: {
                source: "",
                sourceDef: "report.data.dataSource.select._cdata",
                isTable: false,
                def: '<![CDATA["#source#"]]>',
                containsFrame: "false",
                hasChild: false,
                attr: "",
              },
            },
            {
              field: {
                source: "report.data.dataSource.group.dataItem",
                sourceDef: "",
                isTable: true,
                def: 0,
                containsFrame: "false",
                hasChild: false,
                attr: {
                  name: "_attributes.name",
                  class: "_attributes.datatype",
                },
              },
            },
          ],
        },
      ],
      required: [
        "source",
        "sourceDef",
        "isTable",
        "def",
        "containsFrame",
        "hasChild",
        "attr",
        "child",
      ],
      properties: {
        source: {
          $id: "#/properties/jasperReport/properties/source",
          type: "string",
          title: "The source schema",
          description: "An explanation about the purpose of this instance.",
          default: "",
          examples: ["report"],
        },
        sourceDef: {
          $id: "#/properties/jasperReport/properties/sourceDef",
          type: "string",
          title: "The sourceDef schema",
          description: "An explanation about the purpose of this instance.",
          default: "",
          examples: [""],
        },
        isTable: {
          $id: "#/properties/jasperReport/properties/isTable",
          type: "boolean",
          title: "The isTable schema",
          description: "An explanation about the purpose of this instance.",
          default: false,
          examples: [false],
        },
        def: {
          $id: "#/properties/jasperReport/properties/def",
          type: "integer",
          title: "The def schema",
          description: "An explanation about the purpose of this instance.",
          default: 0,
          examples: [0],
        },
        containsFrame: {
          $id: "#/properties/jasperReport/properties/containsFrame",
          type: "string",
          title: "The containsFrame schema",
          description: "An explanation about the purpose of this instance.",
          default: "",
          examples: ["false"],
        },
        hasChild: {
          $id: "#/properties/jasperReport/properties/hasChild",
          type: "boolean",
          title: "The hasChild schema",
          description: "An explanation about the purpose of this instance.",
          default: false,
          examples: [true],
        },
        attr: {
          $id: "#/properties/jasperReport/properties/attr",
          type: "object",
          title: "The attr schema",
          description: "An explanation about the purpose of this instance.",
          default: {},
          examples: [
            {
              name: "report._attributes.name",
            },
          ],
          required: ["name"],
          properties: {
            name: {
              $id: "#/properties/jasperReport/properties/attr/properties/name",
              type: "string",
              title: "The name schema",
              description: "An explanation about the purpose of this instance.",
              default: "",
              examples: ["report._attributes.name"],
            },
          },
          additionalProperties: true,
        },
        child: {
          $id: "#/properties/jasperReport/properties/child",
          type: "array",
          title: "The child schema",
          description: "An explanation about the purpose of this instance.",
          default: [],
          examples: [
            [
              {
                parameter: {
                  source: "report.data.userParameter",
                  isTable: "true",
                  hasChild: true,
                  def: "0",
                  containsFrame: "false",
                  attr: {
                    name: "_attributes.name",
                    class: "_attributes.datatype",
                  },
                },
              },
              {
                defaultValueExpression: {
                  source: "report.data.userParameter",
                  isTable: true,
                  hasChild: false,
                  def: 0,
                  containsFrame: "false",
                  attr: {
                    value: "_attributes.initialValue",
                  },
                },
              },
            ],
          ],
          additionalItems: true,
          items: {
            $id: "#/properties/jasperReport/properties/child/items",
            anyOf: [
              {
                $id: "#/properties/jasperReport/properties/child/items/anyOf/0",
                type: "object",
                title: "The first anyOf schema",
                description:
                  "An explanation about the purpose of this instance.",
                default: {},
                examples: [
                  {
                    parameter: {
                      source: "report.data.userParameter",
                      isTable: "true",
                      hasChild: true,
                      def: "0",
                      containsFrame: "false",
                      attr: {
                        name: "_attributes.name",
                        class: "_attributes.datatype",
                      },
                    },
                  },
                ],
                required: ["parameter"],
                properties: {
                  parameter: {
                    $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter",
                    type: "object",
                    title: "The parameter schema",
                    description:
                      "An explanation about the purpose of this instance.",
                    default: {},
                    examples: [
                      {
                        source: "report.data.userParameter",
                        isTable: "true",
                        hasChild: true,
                        def: "0",
                        containsFrame: "false",
                        attr: {
                          name: "_attributes.name",
                          class: "_attributes.datatype",
                        },
                      },
                    ],
                    required: [
                      "source",
                      "isTable",
                      "hasChild",
                      "def",
                      "containsFrame",
                      "attr",
                    ],
                    properties: {
                      source: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/source",
                        type: "string",
                        title: "The source schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["report.data.userParameter"],
                      },
                      isTable: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/isTable",
                        type: "string",
                        title: "The isTable schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["true"],
                      },
                      hasChild: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/hasChild",
                        type: "boolean",
                        title: "The hasChild schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [true],
                      },
                      def: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/def",
                        type: "string",
                        title: "The def schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["0"],
                      },
                      containsFrame: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/containsFrame",
                        type: "string",
                        title: "The containsFrame schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["false"],
                      },
                      attr: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/attr",
                        type: "object",
                        title: "The attr schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: {},
                        examples: [
                          {
                            name: "_attributes.name",
                            class: "_attributes.datatype",
                          },
                        ],
                        required: ["name", "class"],
                        properties: {
                          name: {
                            $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/attr/properties/name",
                            type: "string",
                            title: "The name schema",
                            description:
                              "An explanation about the purpose of this instance.",
                            default: "",
                            examples: ["_attributes.name"],
                          },
                          class: {
                            $id: "#/properties/jasperReport/properties/child/items/anyOf/0/properties/parameter/properties/attr/properties/class",
                            type: "string",
                            title: "The class schema",
                            description:
                              "An explanation about the purpose of this instance.",
                            default: "",
                            examples: ["_attributes.datatype"],
                          },
                        },
                        additionalProperties: true,
                      },
                    },
                    additionalProperties: true,
                  },
                },
                additionalProperties: true,
              },
              {
                $id: "#/properties/jasperReport/properties/child/items/anyOf/1",
                type: "object",
                title: "The second anyOf schema",
                description:
                  "An explanation about the purpose of this instance.",
                default: {},
                examples: [
                  {
                    defaultValueExpression: {
                      source: "report.data.userParameter",
                      isTable: true,
                      hasChild: false,
                      def: 0,
                      containsFrame: "false",
                      attr: {
                        value: "_attributes.initialValue",
                      },
                    },
                  },
                ],
                required: ["defaultValueExpression"],
                properties: {
                  defaultValueExpression: {
                    $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression",
                    type: "object",
                    title: "The defaultValueExpression schema",
                    description:
                      "An explanation about the purpose of this instance.",
                    default: {},
                    examples: [
                      {
                        source: "report.data.userParameter",
                        isTable: true,
                        hasChild: false,
                        def: 0,
                        containsFrame: "false",
                        attr: {
                          value: "_attributes.initialValue",
                        },
                      },
                    ],
                    required: [
                      "source",
                      "isTable",
                      "hasChild",
                      "def",
                      "containsFrame",
                      "attr",
                    ],
                    properties: {
                      source: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/source",
                        type: "string",
                        title: "The source schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["report.data.userParameter"],
                      },
                      isTable: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/isTable",
                        type: "boolean",
                        title: "The isTable schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [true],
                      },
                      hasChild: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/hasChild",
                        type: "boolean",
                        title: "The hasChild schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [false],
                      },
                      def: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/def",
                        type: "integer",
                        title: "The def schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: 0,
                        examples: [0],
                      },
                      containsFrame: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/containsFrame",
                        type: "string",
                        title: "The containsFrame schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["false"],
                      },
                      attr: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/attr",
                        type: "object",
                        title: "The attr schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: {},
                        examples: [
                          {
                            value: "_attributes.initialValue",
                          },
                        ],
                        required: ["value"],
                        properties: {
                          value: {
                            $id: "#/properties/jasperReport/properties/child/items/anyOf/1/properties/defaultValueExpression/properties/attr/properties/value",
                            type: "string",
                            title: "The value schema",
                            description:
                              "An explanation about the purpose of this instance.",
                            default: "",
                            examples: ["_attributes.initialValue"],
                          },
                        },
                        additionalProperties: true,
                      },
                    },
                    additionalProperties: true,
                  },
                },
                additionalProperties: true,
              },
              {
                $id: "#/properties/jasperReport/properties/child/items/anyOf/2",
                type: "object",
                title: "The third anyOf schema",
                description:
                  "An explanation about the purpose of this instance.",
                default: {},
                examples: [
                  {
                    queryString: {
                      source: "",
                      sourceDef: "report.data.dataSource.select._cdata",
                      isTable: false,
                      def: '<![CDATA["#source#"]]>',
                      containsFrame: "false",
                      hasChild: false,
                      attr: "",
                    },
                  },
                ],
                required: ["queryString"],
                properties: {
                  queryString: {
                    $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString",
                    type: "object",
                    title: "The queryString schema",
                    description:
                      "An explanation about the purpose of this instance.",
                    default: {},
                    examples: [
                      {
                        source: "",
                        sourceDef: "report.data.dataSource.select._cdata",
                        isTable: false,
                        def: '<![CDATA["#source#"]]>',
                        containsFrame: "false",
                        hasChild: false,
                        attr: "",
                      },
                    ],
                    required: [
                      "source",
                      "sourceDef",
                      "isTable",
                      "def",
                      "containsFrame",
                      "hasChild",
                      "attr",
                    ],
                    properties: {
                      source: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/source",
                        type: "string",
                        title: "The source schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: [""],
                      },
                      sourceDef: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/sourceDef",
                        type: "string",
                        title: "The sourceDef schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["report.data.dataSource.select._cdata"],
                      },
                      isTable: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/isTable",
                        type: "boolean",
                        title: "The isTable schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [false],
                      },
                      def: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/def",
                        type: "string",
                        title: "The def schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ['<![CDATA["#source#"]]>'],
                      },
                      containsFrame: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/containsFrame",
                        type: "string",
                        title: "The containsFrame schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["false"],
                      },
                      hasChild: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/hasChild",
                        type: "boolean",
                        title: "The hasChild schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [false],
                      },
                      attr: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/2/properties/queryString/properties/attr",
                        type: "string",
                        title: "The attr schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: [""],
                      },
                    },
                    additionalProperties: true,
                  },
                },
                additionalProperties: true,
              },
              {
                $id: "#/properties/jasperReport/properties/child/items/anyOf/3",
                type: "object",
                title: "The fourth anyOf schema",
                description:
                  "An explanation about the purpose of this instance.",
                default: {},
                examples: [
                  {
                    field: {
                      source: "report.data.dataSource.group.dataItem",
                      sourceDef: "",
                      isTable: true,
                      def: 0,
                      containsFrame: "false",
                      hasChild: false,
                      attr: {
                        name: "_attributes.name",
                        class: "_attributes.datatype",
                      },
                    },
                  },
                ],
                required: ["field"],
                properties: {
                  field: {
                    $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field",
                    type: "object",
                    title: "The field schema",
                    description:
                      "An explanation about the purpose of this instance.",
                    default: {},
                    examples: [
                      {
                        source: "report.data.dataSource.group.dataItem",
                        sourceDef: "",
                        isTable: true,
                        def: 0,
                        containsFrame: "false",
                        hasChild: false,
                        attr: {
                          name: "_attributes.name",
                          class: "_attributes.datatype",
                        },
                      },
                    ],
                    required: [
                      "source",
                      "sourceDef",
                      "isTable",
                      "def",
                      "containsFrame",
                      "hasChild",
                      "attr",
                    ],
                    properties: {
                      source: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/source",
                        type: "string",
                        title: "The source schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["report.data.dataSource.group.dataItem"],
                      },
                      sourceDef: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/sourceDef",
                        type: "string",
                        title: "The sourceDef schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: [""],
                      },
                      isTable: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/isTable",
                        type: "boolean",
                        title: "The isTable schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [true],
                      },
                      def: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/def",
                        type: "integer",
                        title: "The def schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: 0,
                        examples: [0],
                      },
                      containsFrame: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/containsFrame",
                        type: "string",
                        title: "The containsFrame schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: "",
                        examples: ["false"],
                      },
                      hasChild: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/hasChild",
                        type: "boolean",
                        title: "The hasChild schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: false,
                        examples: [false],
                      },
                      attr: {
                        $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/attr",
                        type: "object",
                        title: "The attr schema",
                        description:
                          "An explanation about the purpose of this instance.",
                        default: {},
                        examples: [
                          {
                            name: "_attributes.name",
                            class: "_attributes.datatype",
                          },
                        ],
                        required: ["name", "class"],
                        properties: {
                          name: {
                            $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/attr/properties/name",
                            type: "string",
                            title: "The name schema",
                            description:
                              "An explanation about the purpose of this instance.",
                            default: "",
                            examples: ["_attributes.name"],
                          },
                          class: {
                            $id: "#/properties/jasperReport/properties/child/items/anyOf/3/properties/field/properties/attr/properties/class",
                            type: "string",
                            title: "The class schema",
                            description:
                              "An explanation about the purpose of this instance.",
                            default: "",
                            examples: ["_attributes.datatype"],
                          },
                        },
                        additionalProperties: true,
                      },
                    },
                    additionalProperties: true,
                  },
                },
                additionalProperties: true,
              },
            ],
          },
        },
      },
      additionalProperties: true,
    },
  },
  additionalProperties: true,
};
